name: Docker Image Publish

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.NUGET_PACKAGE_TOKEN }}

      - name: Build the Docker image
        run: |
         docker build -t ghcr.io/revolutionized-iot2/riot2-ui:latest -t ghcr.io/revolutionized-iot2/riot2-ui:${{ github.ref_name }} . --build-arg NUGET_AUTH_TOKEN=${{ secrets.NUGET_PACKAGE_TOKEN }}
         docker push ghcr.io/revolutionized-iot2/riot2-ui:latest
         docker push ghcr.io/revolutionized-iot2/riot2-ui:${{ github.ref_name }}
